language: node_js
node_js:
  - '11'
  - '8'
env:
  - DB=postgres
  - DB=mysql
  - DB=sqlite
sudo: false
install: npm install
before_script:
  - npm install -g codeclimate-test-reporter
  - psql -c 'create database sequelize;' -U postgres
  - mysql -e 'CREATE DATABASE sequelize;'
services:
  - postgresql
